# Site settings
title: "ESE 2018"
email: ese@ifsr.de
emailfsr: fsr@ifsr.de
baseurl: "/2018" # the subpath of your site, e.g. /blog/
url: "https://ese.ifsr.de" # the base hostname & protocol for your site
twitter_username: ifsr
github_username:  fsr
color: "#0D5F98"
year: "2018"

# Global Metatags
metatag:
  de:
    description: "Hier findest du den Ablaufplan und die wichtigsten Informationen der Erstsemestereinf端hrung (ESE) f端r Informatik an der TU Dresden."
    abstract:
    keywords:
    "og:title": "ESE 2018 | FSR Informatik"
    "og:description": "Hier findest du den Ablaufplan und die wichtigsten Informationen der Erstsemestereinf端hrung (ESE) f端r Informatik an der TU Dresden."
    "og:locale":
    "og:locale:alternate":
    "og:image":
    "og:image:secure:url":
    "og:type":
    "og:site_name":
    "og:url":
    "og:type":
    HandheldFriendly: true
  en:
    description: "Here you can find the schedule and most important information of the orientation week (ESE) for Computer Science at TU Dresden."
    abstract:
    keywords:
    "og:title": "ESE 2018 | FSR Computer Science"
    "og:description": "Here you can find the schedule and most important information of the orientation week (ESE) for Computer Science at TU Dresden."
    "og:locale":
    "og:ocale-alternate":
    "og:image":
    "og:secure-url":
    "og:type":
    "og:site_name":
    "og:url":
    "og:type":
    HandheldFriendly: true

# Build settings
markdown: kramdown
source: sources
destination: site


plugins:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-assets
 - jemoji

keep_files:
 - eva/keys
 - eva/logs
 - eva/.htaccess
 - eva/.htusers

exclude:
  - .c9
  - .git

permalink: none

compress_html:
  clippings: all
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []


include: ['_de']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "en-posts"
    values:
      layout: "en-post"
  -
    scope:
      path: ""
      type: "en"
    values:
      layout: "en-page"

collections:
  de-news:
  de-sidebar:
  en-news:
  en-sidebar:
  en:
    output: true
    permalink: en/:path:output_ext

# force usage of digests by Jekyll Assets
assets:
  digest: true

# serve emoji locally to avoid CSP issues
emoji:
  src: "/2018/static/"
