# Site settings
title: "ESE 2015"
email: fsr@ifsr.de
description: > # this means to ignore newlines until "baseurl:"
  Die offizielle Seite der ESE 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ifsr.de
github_username:  fsr

# Build settings
markdown: kramdown

exclude:
  - .c9
  - .git

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "en"
      type: "en-posts"
    values:
      layout: "en-post"
  -
    scope:
      path: "en"
      type: "en"
    values:
      layout: "en-page"

sass:
  style: :compressed

collections:
  news:
  sidebar:
  en-news:
  en-sidebar:
  en-posts:
    output: true
    permalink: en/posts/:path
  en:
    output: true
    permalink: en/:path:output_ext
