# Site settings
title: "ESE 2017 | iFSR"
email: ese@ifsr.de
emailfsr: fsr@ifsr.de
baseurl: "/2017" # the subpath of your site, e.g. /blog/
url: "https://ese.ifsr.de" # the base hostname & protocol for your site
twitter_username: ifsr
github_username:  fsr
color: "#FDC412"
year: "2017"

# Global Metatags
metatag:
  de:
    description: "Die offizielle Seite der ESE 2016. Hier findet Ihr alle wichtigen Informationen über die Erst Semester Einführung der Informatik an der TU Dresden."
    abstract:
    keywords:
    "og:title": "ESE 2016 | iFSR"
    "og:description": "Die offizielle Seite der ESE 2016. Hier findet Ihr alle wichtigen Informationen über die Erst Semester Einführung der Informatik an der TU Dresden."
    "og:locale":
    "og:locale:alternate":
    "og:image":
    "og:image:secure:url":
    "og:type":
    "og:site_name":
    "og:url":
    "og:type":
    HandheldFriendly: true
  en:
    description: "This is the official site of ESE 2016. Here you can find all relevant information about the Erst Semester Einführung of computer science at the TU Dresden."
    abstract:
    keywords:
    "og:title": "ESE 2016 | iFSR"
    "og:description": "This is the official site of ESE 2016. Here you can find all relevant information about the Erst Semester Einführung of computer science at the TU Dresden."
    "og:locale":
    "og:ocale-alternate":
    "og:image":
    "og:secure-url":
    "og:type":
    "og:site_name":
    "og:url":
    "og:type":
    HandheldFriendly: true

# Build settings
markdown: kramdown

plugins:
 - jekyll-coffeescript
 - jekyll-paginate
 - jekyll-assets
 - jemoji

keep_files:
 - eva/keys
 - eva/logs
 - eva/.htaccess
 - eva/.htusers

exclude:
  - .c9
  - .git
  - vendor/bundle

permalink: none

compress_html:
  clippings: all
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []


include: ['_de']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "en-posts"
    values:
      layout: "en-post"
  -
    scope:
      path: ""
      type: "en"
    values:
      layout: "en-page"

sass:
  style: :compressed

collections:
  news:
  sidebar:
  en-news:
  en-sidebar:
  en:
    output: true
    permalink: en/:path:output_ext

# force usage of digests by Jekyll Assets
assets:
  digest: true
