# Site settings
title: "ESE 2015"
email: ese@ifsr.de
emailfsr: fsr@ifsr.de
description: > # this means to ignore newlines until "baseurl:"
  Die offizielle Seite der ESE 2015
baseurl: "/2015" # the subpath of your site, e.g. /blog/
url: "https://ese.ifsr.de" # the base hostname & protocol for your site
twitter_username: ifsr
github_username:  fsr
color: "#573B75"

# Build settings
markdown: kramdown

exclude:
  - .c9
  - .git

permalink: none

compress_html:
  clippings: all
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "en"
      type: "en-posts"
    values:
      layout: "en-post"
  -
    scope:
      path: "en"
      type: "en"
    values:
      layout: "en-page"

sass:
  style: :compressed

collections:
  news:
  sidebar:
  en-news:
  en-sidebar:
  en:
    output: true
    permalink: en/:path:output_ext
